### ISSUE TITLE
Should fire copy event even when `navigator.clipboard` is not implemented

### ISSUE THREAD

**Issue by bennypowers** [github/clipboard-copy-element#14]
When using this element in iOS Safari 12, where `navigator.clipboard` is undefined, the `copy` event is never fired.

Instead, the `copy` event should be fired regardless of which API was used, whether `navigator.clipboard` or `document.execCommand`

thanks

**Comment by dgraham** [comment]
The element dispatches a [`clipboard-copy` event](https://github.com/github/clipboard-copy-element#events) so there is a consistent event regardless of how the copy is performed internally.

**Comment by bennypowers** [comment]
Thanks, I was using an old version
