### ISSUE TITLE
`for` not copying on iOS

### ISSUE THREAD

**Issue by bennypowers** [github/clipboard-copy-element#15]
Please see this repro:

https://warp-nail.glitch.me <- browse to this url on iOS Simulator

https://glitch.com/edit/#!/warp-nail?path=index.html <- source

Note that the other ways to use this element are working on iOS, just not the `for` attr.

Probably has something to do with Safari's strict requirements for `document.execCommand`, as mentioned on this SO: https://stackoverflow.com/questions/34045777/copy-to-clipboard-using-javascript-in-ios

**Comment by muan** [comment]
Released in https://github.com/github/clipboard-copy-element/releases/tag/v1.1.1.

FWIW this issue seem to have been fixed in iOS 13.
