### ISSUE TITLE
Feat: Add Style to the Clipboard Copy Element Website

### ISSUE THREAD

**Issue by dev-phantom** [github/clipboard-copy-element#63]
### current behaviour 
there is no style on the website
![image](https://user-images.githubusercontent.com/72051159/220513561-e41ee43a-a748-422c-84f9-4a895016595c.png)

Kindly add Styles to make the UI more attracting to new Users

**Comment by dev-phantom** [comment]
i can fix this if i get assigned to it

**Comment by keithamus** [comment]
Thanks for the issue @dev-phantom.

We intentionally have not styled the example pages. Styles and such are available on https://primer.style where these components are used. The example page is merely intended to show only the behaviour. 

I'll close this, as I do not think we want to add styles to this page. We can continue discussing it though!
